Btb 41 create search result page
ac-trainees/demostore pull request #20
Opened 2022-04-19 11:45 UTC by NSakuta

# Issue
https://amiconsult.atlassian.net/browse/BTB-XX

## Changes

- 
- 

## Checklist

* [x] I tested the functionality on my local environment.
* [x] I made sure my code is easy to read and understand.
* [x] I provided sufficient automated tests for the code.
* [x] There a no conflicts from my-branch..main.

2022-04-20 08:09 UTC, jolle22 requested changes

2022-04-20 08:09 UTC, jolle22 commented on src/app/search-page/filter-component/filter.component.scss
> +}
This class is also created in:
 header.component.scss
If you need the same css class in more then one component it makes sense to place it in a "global" css file. It should in this path: "src/styles.scss"

2022-04-20 08:12 UTC, jolle22 commented on src/app/search-page/sort-component/sort.component.scss
> +mat-form-field::ng-deep.mat-form-field-flex.ng-tns-c76-3 {
ng-tns-c76-3 looks like a temporary class to me.
Are you sure if your query works after restarting the server?

2022-04-20 09:01 UTC, knicken reviewed
I agree with Jonas and his suggestions regarding the CSS

2022-04-21 10:42 UTC, jolle22 approved these changes

2022-04-21 10:46 UTC, merged